version: '3.8'

volumes:
  voyage_volume:
    name: voyage_volume

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - voyage_volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voyage-server
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs