version: '3.8'

services:
  postgres:
    image: postgres:alpine
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voyage-server
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs